[2023-08-24T01:51:55.814+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 15_trigger_dag_run_operator.task_start manual__2023-08-24T01:51:52.938825+00:00 [queued]>
[2023-08-24T01:51:55.826+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 15_trigger_dag_run_operator.task_start manual__2023-08-24T01:51:52.938825+00:00 [queued]>
[2023-08-24T01:51:55.826+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-08-24T01:51:55.853+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): task_start> on 2023-08-24 01:51:52.938825+00:00
[2023-08-24T01:51:55.861+0000] {standard_task_runner.py:57} INFO - Started process 3208 to run task
[2023-08-24T01:51:55.865+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', '15_trigger_dag_run_operator', 'task_start', 'manual__2023-08-24T01:51:52.938825+00:00', '--job-id', '195', '--raw', '--subdir', 'DAGS_FOLDER/15_trigger_dag_run_operator.py', '--cfg-path', '/tmp/tmpm6016e69']
[2023-08-24T01:51:55.865+0000] {standard_task_runner.py:85} INFO - Job 195: Subtask task_start
[2023-08-24T01:51:55.927+0000] {task_command.py:410} INFO - Running <TaskInstance: 15_trigger_dag_run_operator.task_start manual__2023-08-24T01:51:52.938825+00:00 [running]> on host 05c492c53b17
[2023-08-24T01:51:56.056+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='15_trigger_dag_run_operator' AIRFLOW_CTX_TASK_ID='task_start' AIRFLOW_CTX_EXECUTION_DATE='2023-08-24T01:51:52.938825+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-08-24T01:51:52.938825+00:00'
[2023-08-24T01:51:56.060+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-08-24T01:51:56.061+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', "echo 'Let's START'"]
[2023-08-24T01:51:56.080+0000] {subprocess.py:86} INFO - Output:
[2023-08-24T01:51:56.085+0000] {subprocess.py:93} INFO - /bin/bash: -c: line 1: unexpected EOF while looking for matching `''
[2023-08-24T01:51:56.086+0000] {subprocess.py:93} INFO - /bin/bash: -c: line 2: syntax error: unexpected end of file
[2023-08-24T01:51:56.087+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2023-08-24T01:51:56.102+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 211, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-08-24T01:51:56.108+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=15_trigger_dag_run_operator, task_id=task_start, execution_date=20230824T015152, start_date=20230824T015155, end_date=20230824T015156
[2023-08-24T01:51:56.127+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 195 for task task_start (Bash command failed. The command returned a non-zero exit code 2.; 3208)
[2023-08-24T01:51:56.158+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-08-24T01:51:56.195+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
