[2023-08-24T02:47:35.967+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 16_base_operator.num_corona manual__2023-08-24T02:47:32.557530+00:00 [queued]>
[2023-08-24T02:47:35.982+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 16_base_operator.num_corona manual__2023-08-24T02:47:32.557530+00:00 [queued]>
[2023-08-24T02:47:35.982+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-08-24T02:47:36.003+0000] {taskinstance.py:1327} INFO - Executing <Task(SeoulApiToCsvOperator): num_corona> on 2023-08-24 02:47:32.557530+00:00
[2023-08-24T02:47:36.013+0000] {standard_task_runner.py:57} INFO - Started process 4179 to run task
[2023-08-24T02:47:36.017+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', '16_base_operator', 'num_corona', 'manual__2023-08-24T02:47:32.557530+00:00', '--job-id', '199', '--raw', '--subdir', 'DAGS_FOLDER/16_base_operator.py', '--cfg-path', '/tmp/tmpzkqbib7r']
[2023-08-24T02:47:36.018+0000] {standard_task_runner.py:85} INFO - Job 199: Subtask num_corona
[2023-08-24T02:47:36.082+0000] {task_command.py:410} INFO - Running <TaskInstance: 16_base_operator.num_corona manual__2023-08-24T02:47:32.557530+00:00 [running]> on host 05c492c53b17
[2023-08-24T02:47:36.148+0000] {abstractoperator.py:598} ERROR - Exception rendering Jinja template for task 'num_corona', field 'file_path'. Template: "/opt/***/files/{{ data_inteval_end.in_timezone('Asia/Seoul') | ds_nodash }}"
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 590, in _do_render_template_fields
    seen_oids,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 156, in render_template
    return self._render(template, context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 540, in _render
    return super()._render(template, context, dag=dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 113, in _render
    return render_template_to_string(template, context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/helpers.py", line 288, in render_template_to_string
    return render_template(template, cast(MutableMapping[str, Any], context), native=False)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/helpers.py", line 283, in render_template
    return "".join(nodes)
  File "<template>", line 19, in root
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/sandbox.py", line 326, in getattr
    value = getattr(obj, attribute)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/runtime.py", line 859, in __getattr__
    return self._fail_with_undefined_error()
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/runtime.py", line 852, in _fail_with_undefined_error
    raise self._undefined_exception(self._undefined_message)
jinja2.exceptions.UndefinedError: 'data_inteval_end' is undefined
[2023-08-24T02:47:36.157+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1407, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1531, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2179, in render_templates
    original_task.render_template_fields(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 1254, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 590, in _do_render_template_fields
    seen_oids,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 156, in render_template
    return self._render(template, context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 540, in _render
    return super()._render(template, context, dag=dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 113, in _render
    return render_template_to_string(template, context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/helpers.py", line 288, in render_template_to_string
    return render_template(template, cast(MutableMapping[str, Any], context), native=False)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/helpers.py", line 283, in render_template
    return "".join(nodes)
  File "<template>", line 19, in root
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/sandbox.py", line 326, in getattr
    value = getattr(obj, attribute)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/runtime.py", line 859, in __getattr__
    return self._fail_with_undefined_error()
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/runtime.py", line 852, in _fail_with_undefined_error
    raise self._undefined_exception(self._undefined_message)
jinja2.exceptions.UndefinedError: 'data_inteval_end' is undefined
[2023-08-24T02:47:36.170+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=16_base_operator, task_id=num_corona, execution_date=20230824T024732, start_date=20230824T024735, end_date=20230824T024736
[2023-08-24T02:47:36.185+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 199 for task num_corona ('data_inteval_end' is undefined; 4179)
[2023-08-24T02:47:36.228+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-08-24T02:47:36.260+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
