[2023-08-24T02:48:47.368+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 16_base_operator.num_corona manual__2023-08-24T02:47:32.557530+00:00 [queued]>
[2023-08-24T02:48:47.379+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 16_base_operator.num_corona manual__2023-08-24T02:47:32.557530+00:00 [queued]>
[2023-08-24T02:48:47.380+0000] {taskinstance.py:1308} INFO - Starting attempt 3 of 3
[2023-08-24T02:48:47.399+0000] {taskinstance.py:1327} INFO - Executing <Task(SeoulApiToCsvOperator): num_corona> on 2023-08-24 02:47:32.557530+00:00
[2023-08-24T02:48:47.407+0000] {standard_task_runner.py:57} INFO - Started process 4203 to run task
[2023-08-24T02:48:47.411+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', '16_base_operator', 'num_corona', 'manual__2023-08-24T02:47:32.557530+00:00', '--job-id', '201', '--raw', '--subdir', 'DAGS_FOLDER/16_base_operator.py', '--cfg-path', '/tmp/tmpn8uku0aw']
[2023-08-24T02:48:47.412+0000] {standard_task_runner.py:85} INFO - Job 201: Subtask num_corona
[2023-08-24T02:48:47.466+0000] {task_command.py:410} INFO - Running <TaskInstance: 16_base_operator.num_corona manual__2023-08-24T02:47:32.557530+00:00 [running]> on host 05c492c53b17
[2023-08-24T02:48:47.585+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='16_base_operator' AIRFLOW_CTX_TASK_ID='num_corona' AIRFLOW_CTX_EXECUTION_DATE='2023-08-24T02:47:32.557530+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-08-24T02:47:32.557530+00:00'
[2023-08-24T02:48:47.598+0000] {base.py:73} INFO - Using connection ID 'openapi.seoul.go.kr' for task execution.
[2023-08-24T02:48:47.598+0000] {logging_mixin.py:150} INFO - openapi.seoul.go.kr
[2023-08-24T02:48:47.600+0000] {seoul_api_to_csv_operator.py:36} INFO - 시작: 1
[2023-08-24T02:48:47.600+0000] {seoul_api_to_csv_operator.py:37} INFO - 끝: 1000
[2023-08-24T02:48:47.752+0000] {seoul_api_to_csv_operator.py:36} INFO - 시작: 1001
[2023-08-24T02:48:47.753+0000] {seoul_api_to_csv_operator.py:37} INFO - 끝: 2000
[2023-08-24T02:48:47.872+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/airflow/plugins/operators/seoul_api_to_csv_operator.py", line 49, in execute
    full_df.to_csv(self.file_path + '/' + self.file_name, encoding="utf-8", index=False)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/generic.py", line 3482, in to_csv
    storage_options=storage_options,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/formats/format.py", line 1105, in to_csv
    csv_formatter.save()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/formats/csvs.py", line 243, in save
    storage_options=self.storage_options,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/files/20230824/num_corona.csv'
[2023-08-24T02:48:47.889+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=16_base_operator, task_id=num_corona, execution_date=20230824T024732, start_date=20230824T024847, end_date=20230824T024847
[2023-08-24T02:48:47.904+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 201 for task num_corona ([Errno 2] No such file or directory: '/opt/airflow/files/20230824/num_corona.csv'; 4203)
[2023-08-24T02:48:47.946+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-08-24T02:48:47.983+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
