[2023-08-24T07:08:07.942+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 18_slack_callback.task_exit_1 manual__2023-08-24T07:07:01.551714+00:00 [queued]>
[2023-08-24T07:08:07.956+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 18_slack_callback.task_exit_1 manual__2023-08-24T07:07:01.551714+00:00 [queued]>
[2023-08-24T07:08:07.956+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-08-24T07:08:07.981+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): task_exit_1> on 2023-08-24 07:07:01.551714+00:00
[2023-08-24T07:08:07.991+0000] {standard_task_runner.py:57} INFO - Started process 3218 to run task
[2023-08-24T07:08:07.994+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', '18_slack_callback', 'task_exit_1', 'manual__2023-08-24T07:07:01.551714+00:00', '--job-id', '227', '--raw', '--subdir', 'DAGS_FOLDER/18_slack_callback.py', '--cfg-path', '/tmp/tmpi1ys3dmk']
[2023-08-24T07:08:07.995+0000] {standard_task_runner.py:85} INFO - Job 227: Subtask task_exit_1
[2023-08-24T07:08:08.053+0000] {task_command.py:410} INFO - Running <TaskInstance: 18_slack_callback.task_exit_1 manual__2023-08-24T07:07:01.551714+00:00 [running]> on host 8c493a5ffb5d
[2023-08-24T07:08:08.155+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='18_slack_callback' AIRFLOW_CTX_TASK_ID='task_exit_1' AIRFLOW_CTX_EXECUTION_DATE='2023-08-24T07:07:01.551714+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-08-24T07:07:01.551714+00:00'
[2023-08-24T07:08:08.156+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-08-24T07:08:08.158+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'exit 1']
[2023-08-24T07:08:08.175+0000] {subprocess.py:86} INFO - Output:
[2023-08-24T07:08:08.177+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-08-24T07:08:08.191+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 211, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-08-24T07:08:08.195+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=18_slack_callback, task_id=task_exit_1, execution_date=20230824T070701, start_date=20230824T070807, end_date=20230824T070808
[2023-08-24T07:08:08.205+0000] {base.py:73} INFO - Using connection ID 'conn-slack-***-bot' for task execution.
[2023-08-24T07:08:08.571+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 227 for task task_exit_1 (Bash command failed. The command returned a non-zero exit code 1.; 3218)
[2023-08-24T07:08:08.608+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-08-24T07:08:08.644+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
