[2023-08-18T04:55:50.709+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dags_external_task_sensor.external_task_sensor_a manual__2023-08-18T04:55:47.721833+00:00 [queued]>
[2023-08-18T04:55:50.739+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dags_external_task_sensor.external_task_sensor_a manual__2023-08-18T04:55:47.721833+00:00 [queued]>
[2023-08-18T04:55:50.740+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-08-18T04:55:50.786+0000] {taskinstance.py:1327} INFO - Executing <Task(ExternalTaskSensor): external_task_sensor_a> on 2023-08-18 04:55:47.721833+00:00
[2023-08-18T04:55:50.809+0000] {standard_task_runner.py:57} INFO - Started process 2582 to run task
[2023-08-18T04:55:50.834+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dags_external_task_sensor', 'external_task_sensor_a', 'manual__2023-08-18T04:55:47.721833+00:00', '--job-id', '33', '--raw', '--subdir', 'DAGS_FOLDER/dags_external_task_sensor.py', '--cfg-path', '/tmp/tmpvfwlrsmv']
[2023-08-18T04:55:50.840+0000] {standard_task_runner.py:85} INFO - Job 33: Subtask external_task_sensor_a
[2023-08-18T04:55:50.995+0000] {task_command.py:410} INFO - Running <TaskInstance: dags_external_task_sensor.external_task_sensor_a manual__2023-08-18T04:55:47.721833+00:00 [running]> on host 05c492c53b17
[2023-08-18T04:55:51.157+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dags_external_task_sensor' AIRFLOW_CTX_TASK_ID='external_task_sensor_a' AIRFLOW_CTX_EXECUTION_DATE='2023-08-18T04:55:47.721833+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-08-18T04:55:47.721833+00:00'
[2023-08-18T04:55:51.160+0000] {external_task.py:236} INFO - Poking for tasks ['task_a'] in dag dags_branch_python_operator on 2023-08-17T22:55:47.721833+00:00 ... 
[2023-08-18T04:56:01.199+0000] {external_task.py:236} INFO - Poking for tasks ['task_a'] in dag dags_branch_python_operator on 2023-08-17T22:55:47.721833+00:00 ... 
[2023-08-18T04:56:11.267+0000] {external_task.py:236} INFO - Poking for tasks ['task_a'] in dag dags_branch_python_operator on 2023-08-17T22:55:47.721833+00:00 ... 
[2023-08-18T04:56:21.303+0000] {external_task.py:236} INFO - Poking for tasks ['task_a'] in dag dags_branch_python_operator on 2023-08-17T22:55:47.721833+00:00 ... 
[2023-08-18T04:56:31.327+0000] {external_task.py:236} INFO - Poking for tasks ['task_a'] in dag dags_branch_python_operator on 2023-08-17T22:55:47.721833+00:00 ... 
[2023-08-18T04:56:41.259+0000] {local_task_job_runner.py:292} WARNING - State of this instance has been externally set to restarting. Terminating instance.
[2023-08-18T04:56:41.262+0000] {process_utils.py:135} INFO - Sending Signals.SIGTERM to group 2582. PIDs of all processes in the group: [2582]
[2023-08-18T04:56:41.262+0000] {process_utils.py:86} INFO - Sending the signal Signals.SIGTERM to group 2582
[2023-08-18T04:56:41.262+0000] {taskinstance.py:1517} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-08-18T04:56:41.280+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/sensors/base.py", line 253, in execute
    time.sleep(self._get_next_poke_interval(started_at, run_duration, try_number))
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1519, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2023-08-18T04:56:41.292+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=dags_external_task_sensor, task_id=external_task_sensor_a, execution_date=20230818T045547, start_date=20230818T045550, end_date=20230818T045641
[2023-08-18T04:56:41.323+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 33 for task external_task_sensor_a (Task received SIGTERM signal; 2582)
[2023-08-18T04:56:41.355+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=2582, status='terminated', exitcode=1, started='04:55:50') (2582) terminated with exit code 1
