[2023-08-23T07:36:08.538+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 07_macro.python_task1 manual__2023-08-23T07:31:08.218873+00:00 [queued]>
[2023-08-23T07:36:08.551+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 07_macro.python_task1 manual__2023-08-23T07:31:08.218873+00:00 [queued]>
[2023-08-23T07:36:08.551+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-08-23T07:36:08.575+0000] {taskinstance.py:1327} INFO - Executing <Task(_PythonDecoratedOperator): python_task1> on 2023-08-23 07:31:08.218873+00:00
[2023-08-23T07:36:08.583+0000] {standard_task_runner.py:57} INFO - Started process 6437 to run task
[2023-08-23T07:36:08.586+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', '07_macro', 'python_task1', 'manual__2023-08-23T07:31:08.218873+00:00', '--job-id', '147', '--raw', '--subdir', 'DAGS_FOLDER/07_macro.py', '--cfg-path', '/tmp/tmp1d_v17n2']
[2023-08-23T07:36:08.587+0000] {standard_task_runner.py:85} INFO - Job 147: Subtask python_task1
[2023-08-23T07:36:08.651+0000] {task_command.py:410} INFO - Running <TaskInstance: 07_macro.python_task1 manual__2023-08-23T07:31:08.218873+00:00 [running]> on host 05c492c53b17
[2023-08-23T07:36:08.710+0000] {abstractoperator.py:598} ERROR - Exception rendering Jinja template for task 'python_task1', field 'templates_dict'. Template: {'start_date': "{{ data_interval_end.in_timezone('Asia/Seoul') + macros.dateutil.relativedelta.relativedelta(month=-1, day=1)) | ds }}", 'end_date': "{{ data_interval_end.in_timezone('Asia/Seoul').replace(day=1) + macros.dateutil.relativedelta.relativedelta(days=-1)) | ds }}"}
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 590, in _do_render_template_fields
    seen_oids,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 168, in render_template
    return {k: self.render_template(v, context, jinja_env, oids) for k, v in value.items()}
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 168, in <dictcomp>
    return {k: self.render_template(v, context, jinja_env, oids) for k, v in value.items()}
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 155, in render_template
    template = jinja_env.from_string(value)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 1105, in from_string
    return cls.from_code(self, self.compile(source), gs, None)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<unknown>", line 1, in template
jinja2.exceptions.TemplateSyntaxError: unexpected ')'
[2023-08-23T07:36:08.713+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1407, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1531, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2179, in render_templates
    original_task.render_template_fields(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 1254, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 590, in _do_render_template_fields
    seen_oids,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 168, in render_template
    return {k: self.render_template(v, context, jinja_env, oids) for k, v in value.items()}
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 168, in <dictcomp>
    return {k: self.render_template(v, context, jinja_env, oids) for k, v in value.items()}
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 155, in render_template
    template = jinja_env.from_string(value)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 1105, in from_string
    return cls.from_code(self, self.compile(source), gs, None)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<unknown>", line 1, in template
jinja2.exceptions.TemplateSyntaxError: unexpected ')'
[2023-08-23T07:36:08.724+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=07_macro, task_id=python_task1, execution_date=20230823T073108, start_date=20230823T073608, end_date=20230823T073608
[2023-08-23T07:36:08.740+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 147 for task python_task1 (unexpected ')'; 6437)
[2023-08-23T07:36:08.759+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-08-23T07:36:08.797+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
