[2023-08-23T07:31:10.184+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 07_macro.bash_task manual__2023-08-23T07:31:08.218873+00:00 [queued]>
[2023-08-23T07:31:10.207+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 07_macro.bash_task manual__2023-08-23T07:31:08.218873+00:00 [queued]>
[2023-08-23T07:31:10.208+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-08-23T07:31:10.249+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): bash_task> on 2023-08-23 07:31:08.218873+00:00
[2023-08-23T07:31:10.271+0000] {standard_task_runner.py:57} INFO - Started process 6339 to run task
[2023-08-23T07:31:10.276+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', '07_macro', 'bash_task', 'manual__2023-08-23T07:31:08.218873+00:00', '--job-id', '142', '--raw', '--subdir', 'DAGS_FOLDER/07_macro.py', '--cfg-path', '/tmp/tmpb65numnu']
[2023-08-23T07:31:10.277+0000] {standard_task_runner.py:85} INFO - Job 142: Subtask bash_task
[2023-08-23T07:31:10.352+0000] {task_command.py:410} INFO - Running <TaskInstance: 07_macro.bash_task manual__2023-08-23T07:31:08.218873+00:00 [running]> on host 05c492c53b17
[2023-08-23T07:31:10.420+0000] {abstractoperator.py:598} ERROR - Exception rendering Jinja template for task 'bash_task', field 'env'. Template: {'START_DATE': "{{ data_interval_start.in_timezone('Asia/Seoul') | ds }}", 'END_DATE': "{{ data_interval_end.in_timezone('Asia/Seoul') - macros.datetuil.relativedelta.relativedelta(days=1) | ds }}"}
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 590, in _do_render_template_fields
    seen_oids,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 168, in render_template
    return {k: self.render_template(v, context, jinja_env, oids) for k, v in value.items()}
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 168, in <dictcomp>
    return {k: self.render_template(v, context, jinja_env, oids) for k, v in value.items()}
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 156, in render_template
    return self._render(template, context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 540, in _render
    return super()._render(template, context, dag=dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 113, in _render
    return render_template_to_string(template, context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/helpers.py", line 288, in render_template_to_string
    return render_template(template, cast(MutableMapping[str, Any], context), native=False)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/helpers.py", line 283, in render_template
    return "".join(nodes)
  File "<template>", line 19, in root
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/sandbox.py", line 326, in getattr
    value = getattr(obj, attribute)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/runtime.py", line 859, in __getattr__
    return self._fail_with_undefined_error()
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/runtime.py", line 852, in _fail_with_undefined_error
    raise self._undefined_exception(self._undefined_message)
jinja2.exceptions.UndefinedError: 'module object' has no attribute 'datetuil'
[2023-08-23T07:31:10.426+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1407, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1531, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2179, in render_templates
    original_task.render_template_fields(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 1254, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 590, in _do_render_template_fields
    seen_oids,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 168, in render_template
    return {k: self.render_template(v, context, jinja_env, oids) for k, v in value.items()}
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 168, in <dictcomp>
    return {k: self.render_template(v, context, jinja_env, oids) for k, v in value.items()}
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 156, in render_template
    return self._render(template, context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 540, in _render
    return super()._render(template, context, dag=dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 113, in _render
    return render_template_to_string(template, context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/helpers.py", line 288, in render_template_to_string
    return render_template(template, cast(MutableMapping[str, Any], context), native=False)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/helpers.py", line 283, in render_template
    return "".join(nodes)
  File "<template>", line 19, in root
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/sandbox.py", line 326, in getattr
    value = getattr(obj, attribute)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/runtime.py", line 859, in __getattr__
    return self._fail_with_undefined_error()
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/runtime.py", line 852, in _fail_with_undefined_error
    raise self._undefined_exception(self._undefined_message)
jinja2.exceptions.UndefinedError: 'module object' has no attribute 'datetuil'
[2023-08-23T07:31:10.439+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=07_macro, task_id=bash_task, execution_date=20230823T073108, start_date=20230823T073110, end_date=20230823T073110
[2023-08-23T07:31:10.460+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 142 for task bash_task ('module object' has no attribute 'datetuil'; 6339)
[2023-08-23T07:31:10.488+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-08-23T07:31:10.531+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
